# Generated by Django 3.0.6 on 2020-05-22 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('calories', models.DecimalField(decimal_places=3, max_digits=5)),
                ('steps', models.DecimalField(decimal_places=3, max_digits=5)),
                ('distance', models.DecimalField(decimal_places=3, max_digits=5)),
                ('floors', models.DecimalField(decimal_places=3, max_digits=5)),
                ('minutes_sitting', models.DecimalField(decimal_places=3, max_digits=5)),
                ('minutes_of_slow_activity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('minutes_of_moderate_activity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('minutes_of_intense_activity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('calories_activity', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
