# Generated by Django 2.2 on 2020-06-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('value', models.IntegerField()),
                ('intensitytime', models.TextField()),
                ('intensity', models.IntegerField()),
                ('stepsminute', models.TextField()),
                ('steps', models.IntegerField()),
                ('sleepminute', models.TextField()),
                ('sleepvalue', models.IntegerField()),
                ('sleeplogid', models.BigIntegerField()),
                ('metminute', models.TextField()),
                ('mets', models.IntegerField()),
                ('calminute', models.TextField()),
                ('calories', models.FloatField()),
            ],
        ),
    ]
