# Generated by Django 2.2 on 2020-06-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='calminute',
            field=models.TextField(blank=True, db_column='CalMinute', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='calories',
            field=models.FloatField(blank=True, db_column='Calories', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='intensity',
            field=models.IntegerField(blank=True, db_column='Intensity', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='intensitytime',
            field=models.TextField(blank=True, db_column='IntensityTime', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='metminute',
            field=models.TextField(blank=True, db_column='MetMinute', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='mets',
            field=models.IntegerField(blank=True, db_column='METs', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='sleeplogid',
            field=models.BigIntegerField(blank=True, db_column='SleepLogId', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='sleepminute',
            field=models.TextField(blank=True, db_column='SleepMinute', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='sleepvalue',
            field=models.IntegerField(blank=True, db_column='SleepValue', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='steps',
            field=models.IntegerField(blank=True, db_column='Steps', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='stepsminute',
            field=models.TextField(blank=True, db_column='StepsMinute', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='time',
            field=models.TextField(blank=True, db_column='Time', null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='value',
            field=models.IntegerField(blank=True, db_column='Value', null=True),
        ),
    ]
