# Generated by Django 3.0.6 on 2020-05-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0002_auto_20200522_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='calories_activity',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
