# Generated by Django 3.0.6 on 2020-05-31 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0003_auto_20200522_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activity',
        ),
    ]
