# Generated by Django 3.0.6 on 2020-05-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashborad', '0004_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateField()),
                ('Value', models.FloatField()),
                ('IntensityTime', models.DateField()),
                ('Intensity', models.FloatField()),
                ('StepsMinute', models.FloatField()),
                ('Steps', models.FloatField()),
                ('SleepMinute', models.FloatField()),
                ('SleepValue', models.FloatField()),
                ('SleepLogId', models.FloatField()),
                ('MetMinute', models.FloatField()),
                ('METs', models.FloatField()),
                ('CalMinute', models.FloatField()),
                ('Calories', models.FloatField()),
            ],
            options={
                'db_table': 'fitbit',
            },
        ),
    ]
