# Generated by Django 2.2 on 2020-05-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashborad', '0005_fitbit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('intensitytime', models.TextField(blank=True, null=True)),
                ('intensity', models.TextField(blank=True, null=True)),
                ('stepsminute', models.TextField(blank=True, null=True)),
                ('steps', models.TextField(blank=True, null=True)),
                ('sleepminute', models.TextField(blank=True, null=True)),
                ('sleepvalue', models.TextField(blank=True, null=True)),
                ('sleeplogid', models.TextField(blank=True, null=True)),
                ('metminute', models.TextField(blank=True, null=True)),
                ('mets', models.TextField(blank=True, null=True)),
                ('calminute', models.TextField(blank=True, null=True)),
                ('calories', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'health',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Fitbit',
        ),
    ]
